### ISSUE TITLE
cert manager not issuing due to missing annotations

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#432]
I am getting this error

Not syncing ingress keycloak-server-development/keycloak-server-ingress as it does not contain necessary annotations

This is what my resource looks like

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  namespace: ${KUBE_NAMESPACE}
  labels:
    name: ${APP_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: ${APP_HOST_NAME}
    kubernetes.io/tls-acme: true
    certmanager.k8s.io/issuer: "letsencrypt-staging"
    certmanager.k8s.io/acme-challenge-type: http01

spec:
  tls:
    - hosts:
        - ${APP_HOST_NAME}
      secretName: ${APP_NAME}-tls
  rules:
    - host:  ${APP_HOST_NAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${APP_NAME}-service
              servicePort: 8443


```

What else do I need?

**Comment by anguslees** [comment]
Looks correct to me, except your  `kubernetes.io/tls-acme` value is a boolean and not a string.  Try changing that `true` to `"true"`.  YAML has some hidden sharp spikes :(

Let me know if that change is sufficient.  If not, I'll try to reproduce it locally and go code diving.

**Comment by timuckun** [comment]
I am still getting the same error

not syncing ingress keycloak-server-development/keycloak-server-ingress as it does not contain necessary annotations

Here is my ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  namespace: ${KUBE_NAMESPACE}
  labels:
    name: ${APP_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: ${APP_HOST_NAME}
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: "letsencrypt-staging"
    certmanager.k8s.io/acme-challenge-type: http01

spec:
  tls:
    - hosts:
        - ${APP_HOST_NAME}
      secretName: ${APP_NAME}-tls
  rules:
    - host:  ${APP_HOST_NAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${APP_NAME}-service
              servicePort: 8080
```

I also created a certificate which I don't think should be necessary right?
