### ISSUE TITLE
Documentation for OAuth2 annotations

### ISSUE THREAD

**Issue by dsyer** [bitnami/kube-prod-runtime#734]
You can use the same single-sign on in your apps as the metrics/log stack provided by BKPR. You just have to add 2 annotations:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://auth.$(DOMAIN)/oauth2/start?rd=%2F$server_name$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.$(DOMAIN)/oauth2/auth
```

But this feature doesn't seem to be documented anywhere. It would be good to be able to easily find it in /docs.
