### ISSUE TITLE
How to make the kubeapp login by BKRP keycloak?

### ISSUE THREAD

**Issue by toniz** [bitnami/kube-prod-runtime#788]
1. I install kubeapps as follow:
```
helm install \
  kubeapps --namespace kubeapps \
  --set ingress.enabled=true \
  --set ingress.certManager=true \
  --set ingress.hosts[0].name=kubeapps.xxxx.com \
  --set ingress.hosts[0].tls=true \
  --set ingress.hosts[0].tlsSecret=kubeapps-tls \
  --set mongodb.metrics.enabled=true \
  bitnami/kubeapps --set useHelm3=true
```
2. then modify the ingress as follow:
kubectl -n kubeapps edit ing kubeapps
```
kind: Ingress
metadata:
  annotations:
    kubecfg.ksonnet.io/garbage-collect-tag: kube_prod_runtime
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://auth.ibbwhat.com/oauth2/start?rd=%2F$server_name$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.ibbwhat.com/oauth2/auth 
....
```

3. modify the configMap as follow:
kubectl -n kubeapps edit cm kubeapps-internal-dashboard-config
```
apiVersion: v1
data:
  config.json: |-
    {
      "namespace": "kubeapps",
      "appVersion": "v1.8.2",
      "authProxyEnabled": true,
      "oauthLoginURI": "/oauth2/start",
      "oauthLogoutURI": "/oauth2/sign_out",
      "featureFlags": {"reposPerNamespace":false}
    }

```

4.modify the kube-apiserver add:
```
    - --oidc-issuer-url=https://id.xxx.com/auth/realms/BKPR
    - --oidc-client-id=bkpr
    - --oidc-username-claim=preferred_username
    - --oidc-username-prefix=-
    - --oidc-ca-file=/etc/kubernetes/pki/bkpr.pem
    - --oidc-groups-claim=groups
```
5. then test by kubectl is OK.

But On Browser,  Get https://.../kube/api  is failed, error system:anonymous  401
How can i fixed this error. thank you..
